DELETE FROM plugin WHERE id = '9191';
DELETE FROM plugin_sid where plugin_id = '9191';
DELETE FROM software_cpe where plugin = 'hp_procurve_switch:9191';
INSERT IGNORE INTO software_cpe (cpe, name, version, line, vendor, plugin) VALUES ('cpe:/o:HP:procurve:15.116.0008','procurve','15.116.0008','','HP', 'hp_procurve:9191');
INSERT IGNORE INTO plugin (id, type, name, description, product_type, vendor) VALUES (9191, 1, 'hp_procurve', 'hp_procurve', '24', 'HP');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (9191, 00001, NULL, NULL, 'virtual LAN enabled', 2, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (9191, 00002, NULL, NULL, 'virtual LAN disabled', 2, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (9191, 00061, NULL, NULL, 'Unknown event', 2, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (9191, 00062, NULL, NULL, 'went down without saving crash information', 2, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (9191, 00063, NULL, NULL, 'Mgmt Module went down', 2, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (9191, 00064, NULL, NULL, 'Operator cold reboot from TELNET session', 2, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (9191, 00064, NULL, NULL, 'Operator warm reload', 2, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (9191, 00066, NULL, NULL, 'System booted', 2, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (9191, 00068, NULL, NULL, 'Slot Inserted', 2, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (9191, 00076, NULL, NULL, 'Port is now on-line', 2, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (9191, 00077, NULL, NULL, 'Port is now off-line', 2, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (9191, 00080, NULL, NULL, 'entity enabled', 2, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (9191, 00110, NULL, NULL, 'telnetd service enabled', 2, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (9191, 00131, NULL, NULL, 'tftp transfer completed', 2, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (9191, 00138, NULL, NULL, 'TFTP daemon enabled', 2, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (9191, 00150, NULL, NULL, 'Primary Image updated via network tftp', 2, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (9191, 00163, NULL, NULL, 'Firmware image contains valid signature', 2, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (9191, 00179, NULL, NULL, 'SME SSH request', 2, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (9191, 00274, NULL, NULL, 'PoE controller selftest failure', 2, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (9191, 00327, NULL, NULL, 'Excessive undersized/giant packets', 2, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (9191, 00375, NULL, NULL, 'Slot Downloading', 2, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (9191, 00376, NULL, NULL, 'Slot Download Complete', 2, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (9191, 00400, NULL, NULL, 'Stack Protocol disabled', 2, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (9191, 00410, NULL, NULL, 'SNTP Client enabled', 2, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (9191, 00417, NULL, NULL, 'CDP enabled', 2, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (9191, 00422, NULL, NULL, 'Slot Ready', 2, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (9191, 00433, NULL, NULL, 'Ssh server enabled', 2, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (9191, 00463, NULL, NULL, 'SSL HTTP server enabled on TCP port 443', 2, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (9191, 00567, NULL, NULL, 'PD Other Fault indication', 2, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (9191, 00578, NULL, NULL, 'Unrecoverable fault on PoE controller', 2, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (9191, 00688, NULL, NULL, 'LLDP - enabled', 2, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (9191, 00690, NULL, NULL, 'relay agent feature enabled', 2, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (9191, 00803, NULL, NULL, 'port enabled', 2, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (9191, 00820, NULL, NULL, 'A signature is not stored with the current switch software', 2, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (9191, 00820, NULL, NULL, 'A signature is not stored with the current switch software', 2, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (9191, 998, NULL, NULL, 'User Login', 2, 2);
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (9191, 999, NULL, NULL, 'User Logout', 2, 2);
